### ISSUE TITLE
Does it work on private repo?

### ISSUE THREAD

**Issue by j0k3r** [rullzer/fixupbot#15]
I've added the bot (using the marketplace https://github.com/apps/fixupbot) to some of our privates repos and nothing is showing up in the checks PR.

I was wondering if the bot is working on private repo. Is it?

**Comment by rullzer** [comment]
Good question. I'm not sure I didn't test. I guess it should or maybe I need to request additional permissions.

However I do not have private repos so so testing is a bit hard.

**Comment by j0k3r** [comment]
https://blog.github.com/2019-01-07-new-year-new-github/ 🎉
You can now have a private repo!
